services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    secrets:
      - db_password
      - root_password
      - db_user
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_user

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    secrets:
      - db_password
      - root_password
      - db_user
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_USER_FILE: /run/secrets/db_user


  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  root_password:
    file: ../secrets/db_root_password.txt
  db_user:
    file: ../secrets/credentials.txt
